on:
  workflow_dispatch:
  push:
  schedule:
  - cron: '0 * */1 * *'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        submodules: true
    - name: Build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get update
        sudo apt-get install python3-venv cssmin
        mkdir env
        python3 -m venv env
        source env/bin/activate
        python -m pip install -r requirements.txt
        ./build.sh
        cssmin > dist/theme.css.min < dist/theme.css
        mv dist/theme.css.min dist/theme.css
        echo "xemu.app" > dist/CNAME
    - uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
      with:
        path: dist
  Deploy:
    needs: [Build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
